// 1. Operadores aritméticos

let a = 4;
let b = 2;

// 1.1 Adição
console.log(a + b)  // Retorna: 6

// 1.2 Subtração
console.log(a - b)  // 2

// 1.3 Multiplicação
console.log(a * b)  // 8

// 1.4 Divisão
console.log(a / b)  // 2

// 1.5 Módulo (resto da divisão)
console.log(a % b)  // 0 

// 1.6 Exponenciação
console.log (a ** b) // 16

// 1.7 Incremento
a++;
console.log(a) // 5

// 1.8 Decremento
b--;
console.log(b) // 1


// 2. Operadores de atribuição

// 2.1. Atribuição básica
let n = 6;  
console.log(n)  // Retorna: 6

// 2.2. Atribuição de adição
n += 1    
console.log(n)  // 7

// 2.3. Atribuição de subtração
n -= 1
console.log(n)  // 6

// 2.4. Atribuição de multiplicação
n *= 2
console.log(n)  // 12

// 2.5. Atribuição de divisão
n /= 2
console.log(n)  // 6

// 2.6. Atribuição exponencial
n **= 3  
console.log(n)  // 216

// 2.7. Atribuição de resto
n %= 2
console.log(n)  // 0